### ISSUE TITLE
Slack Notifier Unmarshal Failures - Cloud Build enum for machine types needs E2

### ISSUE THREAD

**Issue by NotNoah** [GoogleCloudPlatform/cloud-build-notifiers#105] opened 2021-03-12 03:15 UTC
`Build: proto: (line 1:1900): invalid value for enum type: "E2_HIGHCPU_8"`

The above error message comes from the slack notifier on image -` us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers/slack:latest` when using the E2_HIGHCPU_8 machineType in cloudbuild

was able to fix this by changing the machineType to use N1_HIGHCPU_8 instead

**Comment by sajid-khan-js** [comment] 2021-03-12 12:55
Get the same issue too.

**Comment by LOZORD** [comment] 2021-03-12 16:44
Hi all, it sounds like the `cloudbuild` package at https://pkg.go.dev/google.golang.org/genproto@v0.0.0-20210312152112-fc591d9ea70f/googleapis/devtools/cloudbuild/v1 is out of date. I'll look into this. For now, the workaround is to switch the machine type.

**Comment by LOZORD** [comment] 2021-03-15 23:11
I'm working on a change in our protobuf publishing pipeline which should hopefully fix this and land sometime this week on the `googleapis` repo and then here as well. Thanks for your patience!

**Comment by LOZORD** [comment] 2021-03-16 19:50
Ok, as of https://github.com/googleapis/googleapis/commit/913f5553d5ff5940cddd8245313136449b2a3571, the new machine types are present in the proto. Now the generate Golang library just needs to catch up. We'll cut new images with that library once it has caught up.

**Comment by LOZORD** [comment] 2021-03-17 18:45
pkg.go.dev now has a genproto version with the new machine types 😌 

https://pkg.go.dev/google.golang.org/genproto@v0.0.0-20210317182105-75c7a8546eb9/googleapis/devtools/cloudbuild/v1#BuildOptions_MachineType

I'll have someone on our team or myself cut new image updates.

**Comment by LOZORD** [comment] 2021-03-19 21:58
Hi all,

`gcb-release/us-east1/cloud-build-notifiers/slack/sha256:1ea0a63d8950a509aa3e0fd4063737e50eb1e100ec6abb5f804a4217c180f17f` should have the new machine type available. Hope this helps!

**Comment by LOZORD** [comment] 2021-03-22 20:30
I'm marking this as fixed. The root cause was that we (the GCB team) hadn't published our proto through the proper channels that the codegen tools use for libraries since at least December. Please file another issue if another weird unmarshalling issue occurs.

**Closed by LOZORD** 2021-03-22 20:30 UTC
Labels: bug
